### ISSUE TITLE
Add support for local API access (custom url)

### ISSUE THREAD

**Issue by fredrike** [molobrakos/tellduslive#1]
It is possible to access the device directly (getting rid of Telldus Live) on **TellStick ZNet Lite (v2)**  [Local API](https://developer.telldus.com/blog/2016/05/24/local-api-for-tellstick-znet-lite-beta-now-in-public-beta)).

It would therefore be great if one could configure tellduslive (and Home Assistant) with a custom URL so Home Assistant can communicate directly with your TellStick ZNet Lite. This option should of course be optional so it does not break old configurations.

**Comment by fredrike** [comment]
And it seems like @skriez already implemented this 😄 . I think it should be merged together with the main code together with Home Assistant.

https://github.com/skriez/tellduslocalapi

**Comment by molobrakos** [comment]
Excellent!
I don't have access to any Telldus ZNet-device so I would not be able to implement or test this.
I would gladly accept any PR that added this functionality to the existing library and HA-component, if possible (it seems like some code can be re-used).

**Comment by fredrike** [comment]
@skriez, do you have interest in merging your code into @molobrakos's and create a unified HA component or is it ok if I reuse your code into new PR's?

@molobrakos, What do you think, https://github.com/molobrakos/tellduslive/compare/master...skriez:master%23diff-7511ef6de052bfa88b2545e960e5842fR78 adds `_getAccessToken()` should we make that conditional if local `url` is set or is there a better solution?

**Comment by molobrakos** [comment]
Maybe adding:
```
def authorize_live_api(pubkey, privkey, secret, token)
def authorize_local_api(ip, token)
```
and then have `__init__ `accept a kwargs-dict and delegate to the correct authentication method depending on supplied params (alternatively leave it to the caller to call the correct authentication method).

Btw, can the ZNet device be autodiscovered by the netdisco library? (there is already some code in there for autodiscovery of Tellstick Net devices) - in that case, the ip might not be neccessary for the user to provide.

**Comment by fredrike** [comment]
> Btw, can the ZNet device be autodiscovered by the netdisco library? (there is already some code in there for autodiscovery of Tellstick Net devices) - in that case, the ip might not be neccessary for the user to provide.

Yes, so it seems 😄

```
tellstick:
[('192.168.0.100',
  'TellstickZnetLiteV2',
  'ACCA5401B5EA',
  'NEDB6EGQCF',
  '1.0.11')]
```

But I'm not sure exactly how to implement this.. 

@mickeprag, is there an interest from Telldus to have support for local Tellstick Znet devices in Home Assistant?

**Comment by mickeprag** [comment]
@fredrike: Yes, of course.

**Comment by fredrike** [comment]
I've added support for Local API connection to HA (https://github.com/molobrakos/home-assistant/compare/master...fredrike:master) and tellduslive (https://github.com/molobrakos/tellduslive/compare/master...fredrike:master) 

@molobrakos Please review the code before I create a pull-request on HA.

**Comment by molobrakos** [comment]
Fantastic! I'll get back later tonight.

**Comment by fredrike** [comment]
@mickeprag: Which device strings are currently supporting Local API? 

Is this sufficient:

```python
        if 'TellstickZnet' in device:  # Only TelldusZnet* devices support local API
```

**Comment by mickeprag** [comment]
All newer generation supports it. Currently:
TellStick ZNet (v1)
TellStick ZNet v2
TellStick Net v2

TellStick (v1) does not support this api.

**Comment by molobrakos** [comment]
Closed by https://github.com/molobrakos/tellduslive/pull/2

**Comment by fredrike** [comment]
@mickeprag what is the timezone for `"expires": 1455295348` in the example given at: http://api.telldus.net/localapi/api/authentication.html#refreshing-a-token? 

We need a solid way to fire a timer to renew the `token` and I don't really trust that users have configured their local clock correctly (or are in sync with your clock). Perhaps it would be good to have an `expires_in` variable from you as well..

**Comment by molobrakos** [comment]
```
datetime.datetime.fromtimestamp(1455295348)
datetime.datetime(2016, 2, 12, 17, 42, 28)
```
I would assume UTC. Actually, if we're not going to rely on the local lock we could either 1) compare with the server time returned in the header (the example you are referring to), or 2) just don't bother at all - we'll just wait for the server to return token expired-error message (whatever that is) during an update request, and in that case send a renewal request and then a new update request.

**Comment by molobrakos** [comment]
Oh, maybe by 2) it is already too late..?

**Comment by mickeprag** [comment]
It should be UTC.
Regarding expires_in, a PR is always welcome ;)

**Comment by mickeprag** [comment]
Fyi
https://github.com/telldus/tellstick-server/blob/master/api/src/api/ApiManager.py#L71

**Comment by n1ck3** [comment]
Hi guys,

This here what you are doing is a great thing! Trying to use Telldus PIRs in HA with Telldus Live Cloud is pointless. 

I am a little confused about a few things though:

1. Will this make it into home assistant's tellduslive component? And if so, do we know when?
1. I am on hassio 58.1. If I put this component in `/config/custom_components/`, will it work as a drop-in replacement for homeassistant's own tellduslive component?

Cheers, and thanks for your work on this!
