### ISSUE TITLE
Support for local device info

### ISSUE THREAD

**Issue by fredrike** [molobrakos/tellduslive#17]
Local devices does not have the `/clients/list` we need a better way to return info about the client than `get_clients()` when connected via `LocalAPISession`. Can the code used for/in discovery (netdisco) be used?

Home-Assistant expect the following:

- ip
- id (could preferrable be mac-address)
- name
- version

**Comment by molobrakos** [comment]
ip/mac can we probably get from the socket. Name and version .. what about "A list of all available functions can be browsed on the device itself. Browse to: http://[ipaddress]/api to list the functions." from http://api.telldus.net/localapi/api.html

**Comment by fredrike** [comment]
The code you wrote for netdisco returns this:

`('192.168.1.10', 'TellstickZnetLiteV2', 'ACCA5401B5EA', 'NEGB6EGQCF', '1.0.12-52-gf0aaf75')`

So I'm just asking for integration of this into tellduslive (udp connection to port 30303):

```
 nc -u 192.168.1.10 30303

TellstickZnetLiteV2:ACCA5401B5EA:NEGB6EGQCF:1.0.12-52-gf0aaf75
```

**Comment by molobrakos** [comment]
Ok, we can use that in case it is not available elsewhere. Since we already have an open connection, I would prefer just to ask directly, if it is possible to get a response with the information we need. What about the api call `system/info`? (found here https://github.com/telldus/tellstick-server/blob/2d4bcacc93d210de74868ff30313725b7e2adf74/telldus/src/telldus/DeviceApiManager.py#L218)

**Comment by molobrakos** [comment]
(Off-topic) maybe of interest to you: https://github.com/quazzie/tellstick-plugin-mqtt-hass

**Comment by fredrike** [comment]
> Ok, we can use that in case it is not available elsewhere. Since we already have an open connection, I would prefer just to ask directly, if it is possible to get a response with the information we need. What about the api call `system/info`? (found here https://github.com/telldus/tellstick-server/blob/2d4bcacc93d210de74868ff30313725b7e2adf74/telldus/src/telldus/DeviceApiManager.py#L218)

Oh, I hate when the information is not documented, I'll start with investigating that one..

> (Off-topic) maybe of interest to you: https://github.com/quazzie/tellstick-plugin-mqtt-hass

Wow, I'm about to build my own. But it's better if someone already have done it :).

**Comment by fredrike** [comment]
This is a way of doing it as a UDP-socket in `LocalAPISession` (I think this would be the easiest way to do it and `system/info` is not public yet).

```python

    def discovery_info(self):
        """Retrive information from discovery socket."""
        import socket
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.settimeout(1)
        sock.sendto(b'D', (self._host, 30303))
        data, (address, _) = sock.recvfrom(1024)
        _LOGGER.error("%s", data)
        entry = data.decode("ascii").split(":")
        # expecting product, mac, activation code, version
        if len(entry) != 4:
            return
        ret = {'ip': address, 'model': entry[0], 'mac': entry[1], 'version': entry[3]}
        _LOGGER.warning("%s",ret)
        return ret

# Session class..
        self._isLocal = True if host else False
    
    def get_clients(self):
        """Request list of clients (Telldus devices) from server."""
        if self._isLocal:
            return self._session.discovery_info()
        res = self._request("clients/list")
        return res.get("client") if res else None
```

**Comment by molobrakos** [comment]
Does `system/info` even work for you? (empty result on mine)

**Comment by fredrike** [comment]
No, I get an "Unknown request". I'll submit a PR with my code above later tonight..
