### ISSUE TITLE
Release 0.10.10 on PyPi differs from release on Github

### ISSUE THREAD

**Issue by berlund** [molobrakos/tellduslive#21]
The version published on [PyPi](https://pypi.org/project/tellduslive/) 0.10.10 is not in sync with the 0.10.10 version on Github. The one here on Github uses `pa-api.telldus.com` which supports TLS1.2 where is the release on PyPi uses `api.telldus.com` which only supports TLS1.0.

This causes TLS hanshake errors on systems with a default minimum TLS version of 1.2, such as Raspian Buster.

**Comment by molobrakos** [comment]
Hopefully fixed now (0.10.11)?
