### ISSUE TITLE
Documentation and example

### ISSUE THREAD

**Issue by hemskgren** [molobrakos/tellduslive#3]
Add documentation and some example of the syntax to turnon/off and dim one device.

**Comment by fredrike** [comment]
The whole telldus live module is rewritten and a new version will be added to HA in the coming weeks.

Which parts are currently unclear @hemskgren ?

**Comment by molobrakos** [comment]
I'd love to include any documentation! Feel free to contribute by submitting some!
The `__main__` function (https://github.com/molobrakos/tellduslive/blob/master/tellduslive.py#L410) contains some code to iterate over all available devices. Turning on/off and dimming is basically then just a matter of calling the relevant method for the device.

**Comment by hemskgren** [comment]
I was thinking it should work to change device thru something like this.

./tellduslive.py device/1806375=turnOn

It look like i need to add that in my own tool using tellduslive.

**Comment by molobrakos** [comment]
No that is not currently possible. You have to write your own tool for that. Or you could submit a PR that adds this functionality (preferably using docopt).

**Comment by molobrakos** [comment]
@hemskgren, a simple command line tool is added here: https://github.com/molobrakos/tellduslive/blob/master/tellduslive
